name = "freegpt"
compatibility_date = "2024-04-03"
main = "app.ts"
node_compat = true

[vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []

#
#Configuration for PRODUCTION environment

[env.production]
name = "freegpt"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []

